export interface Reactions {
  id: string,
  name: string,
}

export enum REACTIONS {
  REACTION_PLUS = "REACTION_PLUS",
  REACTION_MINUS = "REACTION_MINUS",
  REACTION_SMILE = "REACTION_SMILE",
  REACTION_FROWN = "REACTION_FROWN",
  REACTION_LOVE = "REACTION_LOVE",
  REACTION_ANGRY = "REACTION_ANGRY",
}