/* Replace with your SQL commands */
CREATE TABLE IF NOT EXISTS USERS(
  `id` VARCHAR(64) NOT NULL,
  `first_name` VARCHAR(50),
  `last_name` VARCHAR(50),
  `Nick_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `hashed_password` VARCHAR(250) NOT NULL,
  `inscription_time` BIGINT NOT NULL,
  `avatar` VARCHAR(250),
  `biography` VARCHAR(250),
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS CATEGORIES(
  `id` VARCHAR(64) NOT NULL,
  `title` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS SUBCATEGORIES(
  `id` VARCHAR(64) NOT NULL,
  `id_category` VARCHAR(64) NOT NULL,
  `title` TINYTEXT NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS ARTICLES(
  `id` VARCHAR(64) NOT NULL,
  `id_user` VARCHAR(64) NOT NULL,
  `title` TINYTEXT NOT NULL,
  `subtitle` TINYTEXT NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `date_of_write` BIGINT NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS ARTICLE_HAS_CATEGORIES(
  `id` VARCHAR(64) NOT NULL,
  `id_article` VARCHAR(64) NOT NULL,
  `id_subcategory` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS COMMENTS(
  `id` VARCHAR(64) NOT NULL,
  `id_article` VARCHAR(64) NOT NULL,
  `id_user` VARCHAR(64) NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS IMAGES(
  `id` VARCHAR(64) NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `subtitle` VARCHAR(64) NOT NULL,
  `link` TEXT NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS ARTICLE_HAS_IMAGES(
  `id` VARCHAR(64) NOT NULL,
  `id_article` VARCHAR(64) NOT NULL,
  `id_image` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS ROLES(
  `id` VARCHAR(64) NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS USER_HAS_ROLES(
  `id` VARCHAR(64) NOT NULL,
  `id_user` VARCHAR(64) NOT NULL,
  `id_role` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`)
);