export enum ServerResponses {
  SERVER_ERROR = 'SERVER_ERROR',
  CONFLICT = "CONFLICT",
  REQUEST_OK = "REQUEST_OK",
  BAD_REQUEST = "BAD_REQUEST"
}
export enum ServerDetails {
  NO_PASSWORD = "NO_PASSWORD",
  EMAIL_ALREADY_USED = "EMAIL_ALREADY_USED",
  NICKNAME_ALREADY_USED = 'NICKNAME_ALREADY_USED',
  ERROR_CREATION = "ERROR_CREATION",
  CREATION_OK = 'CREATION_OK',
  UPDATE_OK = 'UPDATE_OK',
  ERROR_RETRIEVING = 'ERROR_RETRIEVING'
}